---
- name: create directory /opt/jenkins3/template
  hosts: devserver
  tasks:
    - name: create a recusrive directory
      file:
        path: /opt/jenkins3/template
        state: directory
        owner: root
        group: root
        mode: 0644
        recurse: yes