---
- name: Change file permission
  hosts: devserver
  tasks: 
    - name: Change testfile permission to 777 and user to rahul
      file: /opt/testfile
        owner: rahul
        group: rahul
        mode: "0644"