- hosts: all
  tasks:
    - name: Install the latest version of apache
      apt:
        name: nginx
        state: latest
    - name: Start and enable nginx
      service: 
        name: nginx
        state: started
        enabled: yes
    - name: exec shell
      shell: |
        hostname     
        pwd
